packages:
  - name: pronunciations
    actions:
      - name: pronunciation
        limits: 
          timeout: 5000
          memory: 256
environment:
  SPACES_ENDPOINT: "${SPACES_ENDPOINT}"
  SPACES_NAME: "${SPACES_NAME}"
  SPACES_KEY: "${SPACES_KEY}"
  SPACES_SECRET: "${SPACES_SECRET}"
  DATABASE_URL: "${DATABASE_URL}"
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
  PUBLIC_URL: "${PUBLIC_URL}"
  APP_URL: "${APP_URL}"
  APP_DOMAIN: "${APP_DOMAIN}"